### ISSUE TITLE
ld error (symbols not found) building TMAP 3.0.1 on OS X 10.10

### ISSUE THREAD

**Issue by ghost** [iontorrent/TS#18]
Hello - I am unable to build TMAP 3.0.1 from source on OS X 10.10.5. It fails with this:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tmap] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I tried ./configure, ./configure CC=cc CXX=c++, and ./configure CC=gcc CXX=g++ (as per https://github.com/iontorrent/TMAP/issues/3) but I get the same results. any ideas?

thanks,

Tim

**Comment by uma-ramasubramanian** [comment]
Thank you for your question. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
