### ISSUE TITLE
Potential bug in TVC v. 5.0.2 when a genome.vcf is produced

### ISSUE THREAD

**Issue by idaios** [iontorrent/TS#22]
Dear sirs,
we experience the following awkward situation. We have run two samples with the same reference (hg19) but the produced genome.vcf differ in respect to the reference sequence in certain locations. For example:

 chr1   32052145        .       G       A       183.764 PASS     AF=0.571429;AO=36;DP=63;FAO=36;FDP=63;FR=.;FRO=27;FSAF=16;FSAR=20;FSRF=19;FSRR=8 ;FWDB=-0.0607612;FXX=0;HRUN=1;LEN=1;MLLD=77.9064;OALT=A;OID=.;OMAPALT=A;OPOS=320 52145;OREF=G;PB=0.5;PBP=1;QD=11.6676;RBI=0.0674491;REFB=-0.0729453;REVB=0.029282 4;RO=27;SAF=16;SAR=20;SRF=19;SRR=8;SSEN=0;SSEP=0;SSSB=-0.19967;STB=0.609697;STBP =0.053;TYPE=snp;VARB=0.0471623 GT:GQ:DP:FDP:RO:FRO:AO:FAO:AF:SAR:SAF:SRF:SRR:FSAR:FSAF:FSRF:FSRR  
    0/1:103:63:63:27:27:36:36:0.571429:20:16:19:8:20:16:19:8

 chr1   32052145        .       T       .       0       PASS    DP=185;END=32052348;MAX_DP=206;MIN_DP=173       GT:DP:MIN_DP:MAX_DP     0/0:185:173:206

Obviously, the first sample has a G at 32052145, whereas the second has a T (both are REFERENCE). Can this be a bug of the genome.VCF output option?

I think that it's a mistake of the indexing in the second case

kind regards,

pavlos

**Comment by uma-ramasubramanian** [comment]
Thank you for reporting the issue. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
