### ISSUE TITLE
torentR: Signals of specific wells depends on how they're accessed. Maybe

### ISSUE THREAD

**Issue by bcaller** [iontorrent/TS#23]
I get a different signal with:

`readDat(datpath, chipType="314", row=mask$row[wellid],col=mask$col[wellid])$signal[1,]`

and

`readDat(datpath, chipType="314")$signal[wellid,]`

So I don't know which is the correct signal for that well.
(mask is the result of `readBeadFindMask`, `wellid` is the number of a cell = nCol*r+c)

**Comment by uma-ramasubramanian** [comment]
Thank you for reporting the issue. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
