### ISSUE TITLE
Error in installing file missing

### ISSUE THREAD

**Issue by mano2991** [iontorrent/TS#24]
make  all-recursive
make[1]: Entering directory `/home/bioinformatics/Downloads/TMAP-master'
Making all in .
make[2]: Entering directory`/home/bioinformatics/Downloads/TMAP-master'
depbase=`echo src/util/tmap_alloc.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    gcc -DHAVE_CONFIG_H -I.     -Wall -g -O3 -pthread -msse3 -D_TMAP_BWT_RUN_TYPE=0 -D_USE_KNETFILE -Isrc/samtools -DSAMTOOLS_MAIN -MT src/util/tmap_alloc.o -MD -MP -MF $depbase.Tpo -c -o src/util/tmap_alloc.o src/util/tmap_alloc.c &&\
    mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/util/tmap_definitions.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    gcc -DHAVE_CONFIG_H -I.     -Wall -g -O3 -pthread -msse3 -D_TMAP_BWT_RUN_TYPE=0 -D_USE_KNETFILE -Isrc/samtools -DSAMTOOLS_MAIN -MT src/util/tmap_definitions.o -MD -MP -MF $depbase.Tpo -c -o src/util/tmap_definitions.o src/util/tmap_definitions.c &&\
    mv -f $depbase.Tpo $depbase.Po
In file included from src/util/../seq/tmap_seq.h:8:0,
                 from src/util/tmap_definitions.c:14:
src/util/../seq/tmap_sam.h:6:29: fatal error: ../samtools/bam.h: No such file or directory
 #include "../samtools/bam.h"
                             ^
compilation terminated.
make[2]: **\* [src/util/tmap_definitions.o] Error 1
make[2]: Leaving directory `/home/bioinformatics/Downloads/TMAP-master'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`

**Comment by iluhcm** [comment]
I met the same problem. I have checked out that there is no file under ../samtools/bam.h 

I just wonder if the installation script has been checked before release.

**Comment by uma-ramasubramanian** [comment]
Thank you for reporting the issue. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
