### ISSUE TITLE
Where to download the TMAP 3.6

### ISSUE THREAD

**Issue by dontouchme** [iontorrent/TS#27]
I have downloaded TMAP via git (see README.md from https://github.com/iontorrent/TS/tree/master/Analysis/TMAP) and installed it as well. However, it tuned me out that the TMAP version is 3.4.1 but not 3.6. Did I download the wrong version from wrong the http address? 

Any reply is greatly appreciated,

Thanks,
## 

WM

**Comment by uma-ramasubramanian** [comment]
Thank you for your question. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
