### ISSUE TITLE
IUPAC ambiguity codes

### ISSUE THREAD

**Issue by lituan** [iontorrent/TS#29]
there's a paragrah describing how to handle abiguous DNA bases, but I don't understand why R is converted to C, can you explain this?

Ambiguous IUPAC codes in the reference/target FASTA will be converted to the lexico-
graphically smallest DNA base that is not compatible to the IUPAC code to ensure mini-
mum reference bias. For example, an IUPAC base R, which represents an A or a G, will be
converted to a C. All Ns in the reference will be converted to As. Furthermore, any non-
IUPAC character will be treated as an N. The ambiguity codes will only be re-considered
when calculating the NM and MD SAM record optional tags.

**Comment by uma-ramasubramanian** [comment]
Thank you for your question. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
