### ISSUE TITLE
Is possible to apply soft filtering instead of hard when calling variants?

### ISSUE THREAD

**Issue by Adrianzo** [iontorrent/TS#35]
I'm using the latest TVC standalone with a corresponding parameters.json (germline, pgm, etc).

Is possible to apply soft filtering instead of hard when calling variants?

I'd like to manually inspect each applied filter to gain thoughtful insight.

Thanks!

**Comment by uma-ramasubramanian** [comment]
Thank you for your question. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
