### ISSUE TITLE
Interactive interface of TS

### ISSUE THREAD

**Issue by cweiming** [iontorrent/TS#38]
Hi developer,

I have installed the TS. Basically, I don't have an idea to use TS. It seems to me, I have to write some command lines to run my own iontorrent samples on TS. I have found a document from official website but the document of "torrent suite software 5.6 help" tutors only for interactive interface. I would like to know where I can find the document to guide me to use the TS? Also is possible to install an interactive interface of TS?

Thanks!

--
WM

**Comment by uma-ramasubramanian** [comment]
Thank you for your question. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
