### ISSUE TITLE
How To Call Somatic variants using TS?

### ISSUE THREAD

**Issue by haoziyeung** [iontorrent/TS#40]
Hi there,i have a pair bam data (Tumor and Normal from the same patient), PGM data,i download TS and installed it ,i'm wondering how to call somatic mutaion using TS?

i can't find demo from http://updates.iontorrent.com/tvc_standalone/README.txt
can anybody help me ? 

Thanks a lot..

Oh,here is my command:
`python /gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/bin/variant_caller_pipeline.py --input-bam Ion_B1701/Ion_B1701.bam --reference-fasta /gpfs/users/yanghao/database/ref/hg19_hg38_MT/hg19_hg38_MT.fa --region-bed OCP_Target.bed --normal-bam Ion_B17NC/Ion_B17NC.bam --parameters-file /gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/share/TVC/pluginMedia/parameter_sets/ampliseq_somatic_lowstringency_pgm_parameters.json --output-dir . -g "Sample 1"`

and equal to ::
`/gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/bin/tvc   --output-dir .   --reference "/gpfs/users/yanghao/database/ref/hg19_hg38_MT/hg19_hg38_MT.fa"   --input-bam "Ion_B1701/Ion_B1701.bam","Ion_B17NC/Ion_B17NC.bam"   --sample-name "Sample 1"   --num-threads 12   --target-file "OCP_Target.bed" --parameters-file "/gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/share/TVC/pluginMedia/parameter_sets/ampliseq_somatic_lowstringency_pgm_parameters.json"   --output-vcf "small_variants.vcf"`

and some ERROR occurs:

`[yanghao@c03b01n02 pt1]$ python /gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/bin/variant_caller_pipeline.py --input-bam Ion_B1701/Ion_B1701.bam --reference-fasta /gpfs/users/yanghao/database/ref/hg19_hg38_MT/hg19_hg38_MT.fa --region-bed OCP_Target.bed --normal-bam Ion_B17NC/Ion_B17NC.bam --parameters-file /gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/share/TVC/pluginMedia/parameter_sets/ampliseq_somatic_lowstringency_pgm_parameters.json --output-dir . -g "Sample 1"
[ Wed 2018-03-21 14:00:13 CST ] Using tvc      binary: /gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/bin/tvc
[ Wed 2018-03-21 14:00:13 CST ] Using tvcutils binary: /gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/bin/tvcutils
[ Wed 2018-03-21 14:00:13 CST ] Using tmap     binary: tmap
[ Wed 2018-03-21 14:00:13 CST ] Calling small INDELs and SNPs using tvc ...
[ Wed 2018-03-21 14:00:13 CST ]
[ Wed 2018-03-21 14:00:13 CST ] Task    : Call small indels and SNPs
[ Wed 2018-03-21 14:00:13 CST ] Command : /gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/bin/tvc   --output-dir .   --reference "/gpfs/users/yanghao/database/ref/hg19_hg38_MT/hg19_hg38_MT.fa"   --input-bam "Ion_B1701/Ion_B1701.bam","Ion_B17NC/Ion_B17NC.bam"   --sample-name "Sample 1"   --num-threads 12   --target-file "OCP_Target.bed" --parameters-file "/gpfs/users/yanghao/software/tvc-5.8.0-CentOS_7.2.1511_x86_64-binary/share/TVC/pluginMedia/parameter_sets/ampliseq_somatic_lowstringency_pgm_parameters.json"   --output-vcf "small_variants.vcf"
[ Wed 2018-03-21 14:00:13 CST ]
tvc 5.8-0 (805fda4-c69c74d) - Torrent Variant Caller

TVC: Floating point exceptions enabled.
INFO: No sse VCF file specified via -l,--sse-vcf
INFO: No input VCF (Hotspot) file specified via -c,--input-vcf
                       error-motifs =            (string, parameters json file)
INFO: Systematic error motif file not specified via -e
                      hp-max-length =          8 (integer, parameters json file)
                 sse-prob-threshold =          1 (double,  parameters json file)
     min-ratio-reads-non-sse-strand =        0.2 (double,  builtin default)
          sse-relative-safety-level =      0.025 (double,  builtin default)
                 do-snp-realignment =      false (boolean, parameters json file)
                 do-mnp-realignment =      false (boolean, parameters json file)
              realignment-threshold =          0 (double,  parameters json file)
                   indel-as-hpindel =      false (boolean, parameters json file)
                      hp-indel-hrun =      -1,-1 (int,  builtin default)
                         hp-ins-len =      -1,-1 (int,  builtin default)
                         hp-del-len =      -1,-1 (int,  builtin default)
            data-quality-stringency =         10 (double,  parameters json file)
           read-rejection-threshold =        0.5 (double,  builtin default)
                  use-position-bias =      false (boolean, parameters json file)
         position-bias-ref-fraction =       0.05 (double,  parameters json file)
                      position-bias =       0.75 (double,  parameters json file)
                 position-bias-pval =       0.05 (double,  parameters json file)
                     use-lod-filter =      false (boolean, builtin default)
                     lod-multiplier =        0.6 (double,  builtin default)
                    tag-sim-max-cov =         20 (integer, builtin default)
             downsample-to-coverage =       2000 (integer, parameters json file)
                         tune-sbias =       0.01 (double,  builtin default)
       suppress-reference-genotypes =       true (boolean, builtin default)
          suppress-nocall-genotypes =       true (boolean, builtin default)
                  suppress-no-calls =       true (boolean, builtin default)
                          heal-snps =       true (boolean, builtin default)
        cleanup-unlikely-candidates =       true (boolean, builtin default)
                         report-ppa =      false (boolean, parameters json file)
                hotspots-as-de-novo =      false (boolean, builtin default)
                    disable-filters =      false (boolean, builtin default)
              fd-nonsnp-min-var-cov =          0 (integer, builtin default)
                       use-fd-param =      false (boolean, parameters json file)
                   min-ratio-for-fd =        0.1 (double,  parameters json file)
            snp-min-cov-each-strand =          4 (integer, parameters json file)
              snp-min-variant-score =          6 (double,  parameters json file)
                snp-min-allele-freq =       0.02 (double,  parameters json file)
                   snp-min-coverage =        100 (integer, parameters json file)
               snp-min-var-coverage =          0 (integer, builtin default)
                    snp-strand-bias =       0.95 (double,  parameters json file)
               snp-strand-bias-pval =       0.01 (double,  parameters json file)
Retrieving the snp parameters from the command line and parameter_json["torrent_variant_caller"]["snp"]:
            snp-min-cov-each-strand =          4 (integer, builtin default)
              snp-min-variant-score =          6 (double,  builtin default)
                snp-min-allele-freq =       0.02 (double,  builtin default)
                   snp-min-coverage =        100 (integer, builtin default)
               snp-min-var-coverage =          0 (integer, builtin default)
                    snp-strand-bias =       0.95 (double,  builtin default)
               snp-strand-bias-pval =       0.01 (double,  builtin default)
(Note): Here, "builtin default" may be referred to as the the parameter has been set previously.
Retrieving snp parameter set complete.
            mnp-min-cov-each-strand =          4 (integer, parameters json file)
              mnp-min-variant-score =          6 (double,  parameters json file)
                mnp-min-allele-freq =       0.02 (double,  parameters json file)
                   mnp-min-coverage =        100 (integer, parameters json file)
               mnp-min-var-coverage =          0 (integer, builtin default)
                    mnp-strand-bias =       0.95 (double,  parameters json file)
               mnp-strand-bias-pval =       0.01 (double,  parameters json file)
Retrieving the mnp parameters from the command line and parameter_json["torrent_variant_caller"]["mnp"]:
            mnp-min-cov-each-strand =          4 (integer, builtin default)
              mnp-min-variant-score =          6 (double,  builtin default)
                mnp-min-allele-freq =       0.02 (double,  builtin default)
                   mnp-min-coverage =        100 (integer, builtin default)
               mnp-min-var-coverage =          0 (integer, builtin default)
                    mnp-strand-bias =       0.95 (double,  builtin default)
               mnp-strand-bias-pval =       0.01 (double,  builtin default)
(Note): Here, "builtin default" may be referred to as the the parameter has been set previously.
Retrieving mnp parameter set complete.
          indel-min-cov-each-strand =          4 (integer, parameters json file)
            indel-min-variant-score =          6 (double,  parameters json file)
              indel-min-allele-freq =       0.02 (double,  parameters json file)
                 indel-min-coverage =        100 (integer, parameters json file)
             indel-min-var-coverage =          0 (integer, builtin default)
                  indel-strand-bias =        0.9 (double,  parameters json file)
             indel-strand-bias-pval =          1 (double,  parameters json file)
Retrieving the indel parameters from the command line and parameter_json["torrent_variant_caller"]["indel"]:
          indel-min-cov-each-strand =          4 (integer, builtin default)
            indel-min-variant-score =          6 (double,  builtin default)
              indel-min-allele-freq =       0.02 (double,  builtin default)
                 indel-min-coverage =        100 (integer, builtin default)
             indel-min-var-coverage =          0 (integer, builtin default)
                  indel-strand-bias =        0.9 (double,  builtin default)
             indel-strand-bias-pval =          1 (double,  builtin default)
(Note): Here, "builtin default" may be referred to as the the parameter has been set previously.
Retrieving indel parameter set complete.

Retrieving the indel parameters that will be propagate to the fd-0 parameters:
          indel-min-cov-each-strand =          4 (integer, parameters json file)
            indel-min-variant-score =          6 (double,  parameters json file)
              indel-min-allele-freq =       0.02 (double,  parameters json file)
                 indel-min-coverage =        100 (integer, parameters json file)
             indel-min-var-coverage =          0 (integer, builtin default)
                  indel-strand-bias =        0.9 (double,  parameters json file)
             indel-strand-bias-pval =          1 (double,  parameters json file)
Translating the above indel parameters to the fd-0 parameters.
Retrieving the fd-0 parameters from the command line and parameter_json["torrent_variant_caller"]["fd_0"]:
           fd-0-min-cov-each-strand =          4 (integer, builtin default)
             fd-0-min-variant-score =          6 (double,  builtin default)
               fd-0-min-allele-freq =       0.02 (double,  builtin default)
                  fd-0-min-coverage =        100 (integer, builtin default)
              fd-0-min-var-coverage =          0 (integer, builtin default)
                   fd-0-strand-bias =        0.9 (double,  builtin default)
              fd-0-strand-bias-pval =          1 (double,  builtin default)
(Note): Here, "builtin default" may be referred to as the the parameter has been set previously.
Retrieving fd-0 parameter set complete.

Retrieving the snp parameters that will be propagate to the fd-5 parameters:
            snp-min-cov-each-strand =          4 (integer, parameters json file)
              snp-min-variant-score =          6 (double,  parameters json file)
                snp-min-allele-freq =       0.02 (double,  parameters json file)
                   snp-min-coverage =        100 (integer, parameters json file)
               snp-min-var-coverage =          0 (integer, builtin default)
                    snp-strand-bias =       0.95 (double,  parameters json file)
               snp-strand-bias-pval =       0.01 (double,  parameters json file)
Translating the above snp parameters to the fd-5 parameters.
Retrieving the fd-5 parameters from the command line and parameter_json["torrent_variant_caller"]["fd_5"]:
           fd-5-min-cov-each-strand =          4 (integer, builtin default)
             fd-5-min-variant-score =          6 (double,  builtin default)
               fd-5-min-allele-freq =       0.02 (double,  builtin default)
                  fd-5-min-coverage =        100 (integer, builtin default)
              fd-5-min-var-coverage =          0 (integer, builtin default)
                   fd-5-strand-bias =       0.95 (double,  builtin default)
              fd-5-strand-bias-pval =       0.01 (double,  builtin default)
(Note): Here, "builtin default" may be referred to as the the parameter has been set previously.
Retrieving fd-5 parameter set complete.

Retrieving the mnp parameters that will be propagate to the fd-10 parameters:
            mnp-min-cov-each-strand =          4 (integer, parameters json file)
              mnp-min-variant-score =          6 (double,  parameters json file)
                mnp-min-allele-freq =       0.02 (double,  parameters json file)
                   mnp-min-coverage =        100 (integer, parameters json file)
               mnp-min-var-coverage =          0 (integer, builtin default)
                    mnp-strand-bias =       0.95 (double,  parameters json file)
               mnp-strand-bias-pval =       0.01 (double,  parameters json file)
Translating the above mnp parameters to the fd-10 parameters.
Retrieving the fd-10 parameters from the command line and parameter_json["torrent_variant_caller"]["fd_10"]:
          fd-10-min-cov-each-strand =          4 (integer, builtin default)
            fd-10-min-variant-score =          6 (double,  builtin default)
              fd-10-min-allele-freq =       0.02 (double,  builtin default)
                 fd-10-min-coverage =        100 (integer, builtin default)
             fd-10-min-var-coverage =          0 (integer, builtin default)
                  fd-10-strand-bias =       0.95 (double,  builtin default)
             fd-10-strand-bias-pval =       0.01 (double,  builtin default)
(Note): Here, "builtin default" may be referred to as the the parameter has been set previously.
Retrieving fd-10 parameter set complete.
        hotspot-min-cov-each-strand =          4 (integer, parameters json file)
          hotspot-min-variant-score =          6 (double,  parameters json file)
            hotspot-min-allele-freq =       0.02 (double,  parameters json file)
               hotspot-min-coverage =        100 (integer, parameters json file)
           hotspot-min-var-coverage =          0 (integer, builtin default)
                hotspot-strand-bias =       0.95 (double,  parameters json file)
           hotspot-strand-bias-pval =       0.01 (double,  parameters json file)
Retrieving the hotspot parameters from the command line and parameter_json["torrent_variant_caller"]["hotspot"]:
        hotspot-min-cov-each-strand =          4 (integer, builtin default)
          hotspot-min-variant-score =          6 (double,  builtin default)
            hotspot-min-allele-freq =       0.02 (double,  builtin default)
               hotspot-min-coverage =        100 (integer, builtin default)
           hotspot-min-var-coverage =          0 (integer, builtin default)
                hotspot-strand-bias =       0.95 (double,  builtin default)
           hotspot-strand-bias-pval =       0.01 (double,  builtin default)
(Note): Here, "builtin default" may be referred to as the the parameter has been set previously.
Retrieving hotspot parameter set complete.
                  max-flows-to-test =         10 (integer, parameters json file)
                 min-delta-for-flow =        0.1 (double,  builtin default)
               prediction-precision =          1 (double,  parameters json file)
                outlier-probability =      0.005 (double,  parameters json file)
            germline-prior-strength =          0 (double,  builtin default)
                       heavy-tailed =          3 (integer, parameters json file)
                       adjust-sigma =      false (boolean, builtin default)
         filter-unusual-predictions =       0.12 (double,  parameters json file)
             soft-clip-bias-checker =        0.1 (double,  builtin default)
        filter-deletion-predictions =        0.2 (double,  parameters json file)
       filter-insertion-predictions =        0.2 (double,  parameters json file)
                   max-detail-level =          0 (integer, builtin default)
     min-detail-level-for-fast-scan =          0 (integer, parameters json file)
               try-few-restart-freq =      false (boolean, builtin default)
           shift-likelihood-penalty =        0.3 (double,  builtin default)
                minimum-sigma-prior =      0.085 (double,  builtin default)
                  slope-sigma-prior =     0.0084 (double,  builtin default)
                 sigma-prior-weight =          1 (double,  builtin default)
                             k-zero =          3 (double,  builtin default)
                        num-threads =         12 (integer, command line option)
            num-variants-per-thread =        250 (integer, builtin default)
                 use-sse-basecaller =       true (boolean, builtin default)
                 do-json-diagnostic =      false (boolean, builtin default)
              do-minimal-diagnostic =      false (boolean, builtin default)
       process-input-positions-only =      false (boolean, builtin default)
             suppress-recalibration =      false (boolean, parameters json file)
              resolve-clipped-bases =      false (boolean, builtin default)
                 use-sse-basecaller =       true (boolean, builtin default)
                  do-indel-assembly =       true (boolean, builtin default)
       output-multi-min-allele-freq =      false (boolean, builtin default)
              multi-min-allele-freq = 0.05,0.1,0.15,0.2 (float,  builtin default)
                  suppress-mol-tags =      false (boolean, builtin default)
                   min-tag-fam-size =          3 (integer, builtin default)
             indel-func-size-offset =          0 (integer, builtin default)
                    tag-trim-method = sloppy-trim (string, builtin default)
                   min-cov-fraction =          0 (double,  builtin default)
                       allow-indels =       true (boolean, parameters json file)
                         allow-snps =       true (boolean, parameters json file)
                         allow-mnps =       true (boolean, parameters json file)
                      allow-complex =      false (boolean, parameters json file)
            merge-variant-lookahead =         -1 (integer, builtin default)
                allele-cigar-output =      false (boolean, builtin default)
                  left-align-indels =      false (boolean, builtin default)
                 use-best-n-alleles =          2 (integer, builtin default)
          use-best-n-nonsnp-alleles =          0 (integer, builtin default)
                        max-alt-num =         20 (integer, builtin default)
              use-input-allele-only =      false (boolean, builtin default)
                     min-mapping-qv =          4 (integer, parameters json file)
                     read-snp-limit =         10 (integer, parameters json file)
         read-max-mismatch-fraction =          1 (double,  parameters json file)
                read-mismatch-limit =          0 (integer, builtin default)
                    max-complex-gap =          1 (integer, builtin default)
            gen-min-alt-allele-freq =       0.01 (double,  parameters json file)
                   gen-min-coverage =          6 (integer, parameters json file)
      gen-min-indel-alt-allele-freq =       0.01 (double,  parameters json file)
                    override-limits =      false (boolean, builtin default)
prefix-exclude = 6
Limit check parameter data-quality-stringency: lim. 0 <= 10? OK!
Limit check parameter read-rejection-threshold: lim. 0 <= 0.5 <= lim. 1? OK!
Limit check parameter downsample-to-coverage: lim. 20 <= 2000 <= lim. 200000? OK!
Limit check parameter position-bias-ref-fraction: lim. 0 <= 0.05 <= lim. 1? OK!
Limit check parameter position-bias: lim. 0 <= 0.75 <= lim. 1? OK!
Limit check parameter position-bias-pval: lim. 0 <= 0.05 <= lim. 1? OK!
Limit check parameter tune-sbias: lim. 0.001 <= 0.01 <= lim. 1000? OK!
Limit check parameter lod-multiplier: lim. 0 <= 0.6? OK!
Limit check parameter tag-sim-max-cov: lim. 0 <= 20? OK!
Limit check parameter min-read-ratio-for-fd: lim. 0 <= 0.1 <= lim. 1? OK!
Limit check parameter fd-nonsnp-min-var-cov: lim. 0 <= 0? OK!
Limit check parameter hp-max-length: lim. 1 <= 8? OK!
Limit check parameter sse-prob-threshold: lim. 0 <= 1 <= lim. 1? OK!
Limit check parameter min-ratio-reads-non-sse-strand: lim. 0 <= 0.2 <= lim. 1? OK!
Limit check parameter sse-relative-safety-level: lim. 0 <= 0.025 <= lim. 1? OK!
Limit check parameter realignment-threshold: lim. 0 <= 0 <= lim. 1? OK!
Size check parameters hp-indel-hrun, hp-ins-len, hp-del-len: hp_indel_hrun.size()==hp_ins_len.size()==hp_del_len.size()? OK!
Limit check parameter snp-min-cov-each-strand: lim. 0 <= 4? OK!
Limit check parameter snp-min-variant-score: lim. 0 <= 6? OK!
Limit check parameter snp-min-allele-freq: lim. 0 <= 0.02 <= lim. 1? OK!
Limit check parameter snp-min-coverage: lim. 0 <= 100? OK!
Limit check parameter snp-strand-bias: lim. 0.5 <= 0.95 <= lim. 1? OK!
Limit check parameter snp-strand-bias-pval: lim. 0 <= 0.01 <= lim. 1? OK!
Limit check parameter snp-min-var-coverage: lim. 0 <= 0? OK!
Limit check parameter mnp-min-cov-each-strand: lim. 0 <= 4? OK!
Limit check parameter mnp-min-variant-score: lim. 0 <= 6? OK!
Limit check parameter mnp-min-allele-freq: lim. 0 <= 0.02 <= lim. 1? OK!
Limit check parameter mnp-min-coverage: lim. 0 <= 100? OK!
Limit check parameter mnp-strand-bias: lim. 0.5 <= 0.95 <= lim. 1? OK!
Limit check parameter mnp-strand-bias-pval: lim. 0 <= 0.01 <= lim. 1? OK!
Limit check parameter mnp-min-var-coverage: lim. 0 <= 0? OK!
Limit check parameter indel-min-cov-each-strand: lim. 0 <= 4? OK!
Limit check parameter indel-min-variant-score: lim. 0 <= 6? OK!
Limit check parameter indel-min-allele-freq: lim. 0 <= 0.02 <= lim. 1? OK!
Limit check parameter indel-min-coverage: lim. 0 <= 100? OK!
Limit check parameter indel-strand-bias: lim. 0.5 <= 0.9 <= lim. 1? OK!
Limit check parameter indel-strand-bias-pval: lim. 0 <= 1 <= lim. 1? OK!
Limit check parameter indel-min-var-coverage: lim. 0 <= 0? OK!
Limit check parameter hotspot-min-cov-each-strand: lim. 0 <= 4? OK!
Limit check parameter hotspot-min-variant-score: lim. 0 <= 6? OK!
Limit check parameter hotspot-min-allele-freq: lim. 0 <= 0.02 <= lim. 1? OK!
Limit check parameter hotspot-min-coverage: lim. 0 <= 100? OK!
Limit check parameter hotspot-strand-bias: lim. 0.5 <= 0.95 <= lim. 1? OK!
Limit check parameter hotspot-strand-bias-pval: lim. 0 <= 0.01 <= lim. 1? OK!
Limit check parameter hotspot-min-var-coverage: lim. 0 <= 0? OK!
Limit check parameter fd-0-min-cov-each-strand: lim. 0 <= 4? OK!
Limit check parameter fd-0-min-variant-score: lim. 0 <= 6? OK!
Limit check parameter fd-0-min-allele-freq: lim. 0 <= 0.02 <= lim. 1? OK!
Limit check parameter fd-0-min-coverage: lim. 0 <= 100? OK!
Limit check parameter fd-0-strand-bias: lim. 0.5 <= 0.9 <= lim. 1? OK!
Limit check parameter fd-0-strand-bias-pval: lim. 0 <= 1 <= lim. 1? OK!
Limit check parameter fd-0-min-var-coverage: lim. 0 <= 0? OK!
Limit check parameter fd-5-min-cov-each-strand: lim. 0 <= 4? OK!
Limit check parameter fd-5-min-variant-score: lim. 0 <= 6? OK!
Limit check parameter fd-5-min-allele-freq: lim. 0 <= 0.02 <= lim. 1? OK!
Limit check parameter fd-5-min-coverage: lim. 0 <= 100? OK!
Limit check parameter fd-5-strand-bias: lim. 0.5 <= 0.95 <= lim. 1? OK!
Limit check parameter fd-5-strand-bias-pval: lim. 0 <= 0.01 <= lim. 1? OK!
Limit check parameter fd-5-min-var-coverage: lim. 0 <= 0? OK!
Limit check parameter fd-10-min-cov-each-strand: lim. 0 <= 4? OK!
Limit check parameter fd-10-min-variant-score: lim. 0 <= 6? OK!
Limit check parameter fd-10-min-allele-freq: lim. 0 <= 0.02 <= lim. 1? OK!
Limit check parameter fd-10-min-coverage: lim. 0 <= 100? OK!
Limit check parameter fd-10-strand-bias: lim. 0.5 <= 0.95 <= lim. 1? OK!
Limit check parameter fd-10-strand-bias-pval: lim. 0 <= 0.01 <= lim. 1? OK!
Limit check parameter fd-10-min-var-coverage: lim. 0 <= 0? OK!
Limit check parameter max-flows-to-test: lim. 1 <= 10 <= lim. 100? OK!
Limit check parameter min-delta-for-flow: lim. 0.01 <= 0.1 <= lim. 0.5? OK!
Limit check parameter prediction-precision: lim. 0.1 <= 1? OK!
Limit check parameter outlier-probability: lim. 1e-07 <= 0.005 <= lim. 1? OK!
Limit check parameter germline-prior-strength: lim. 0 <= 0 <= lim. 1000? OK!
Limit check parameter heavy-tailed: lim. 1 <= 3? OK!
Limit check parameter filter-unusual-predictions: lim. 0 <= 0.12? OK!
Limit check parameter soft-clip-bias-checker: lim. 0 <= 0.1 <= lim. 1? OK!
Limit check parameter filter-deletion-predictions: lim. 0 <= 0.2? OK!
Limit check parameter filter-insertion-predictions: lim. 0 <= 0.2? OK!
Limit check parameter max-detail-level: lim. 0 <= 0 <= lim. 10000? OK!
Limit check parameter min-detail-level-for-fast-scan: lim. 0 <= 0? OK!
Limit check parameter shift-likelihood-penalty: lim. 0.01 <= 0.3? OK!
Limit check parameter minimum-sigma-prior: lim. 0.01 <= 0.085? OK!
Limit check parameter slope-sigma-prior: lim. 0 <= 0.0084? OK!
Limit check parameter sigma-prior-weight: lim. 0.01 <= 1? OK!
Limit check parameter k-zero: lim. 0 <= 3? OK!
Limit check parameter num-threads: lim. 1 <= 12 <= lim. 128? OK!
Limit check parameter num-variants-per-thread: lim. 1 <= 250 <= lim. 10000? OK!
Limit check parameter multi-min-allele-freq[0]: lim. 0 <= 0.05 <= lim. 1? OK!
Limit check parameter multi-min-allele-freq[1]: lim. 0 <= 0.1 <= lim. 1? OK!
Limit check parameter multi-min-allele-freq[2]: lim. 0 <= 0.15 <= lim. 1? OK!
Limit check parameter multi-min-allele-freq[3]: lim. 0 <= 0.2 <= lim. 1? OK!
Limit check parameter min-cov-fraction: lim. 0 <= 0 <= lim. 1? OK!
Limit check parameter use-best-n-alleles: lim. 0 <= 2 <= lim. 20? OK!
Limit check parameter use-best-n-nonsnp-alleles: lim. 0 <= 0 <= lim. 20? OK!
Limit check parameter min-mapping-qv: lim. 0 <= 4? OK!
Limit check parameter read-snp-limit: lim. 0 <= 10? OK!
Limit check parameter read-max-mismatch-fraction: lim. 0 <= 1 <= lim. 1? OK!
Limit check parameter read-mismatch-limit: lim. 0 <= 0? OK!
Limit check parameter gen-min-alt-allele-freq: lim. 0 <= 0.01 <= lim. 1? OK!
Limit check parameter gen-min-coverage: lim. 0 <= 6? OK!
Limit check parameter max-alt-num: lim. 1 <= 20? OK!
Limit check parameter gen-min-indel-alt-allele-freq: lim. 0 <= 0.01 <= lim. 1? OK!
Limit check parameter tag-trim-method: lim. 0 <= 1 <= lim. 1? OK!
Limit check parameter min-tag-fam-size: lim. 1 <= 3? OK!
Limit check parameter indel-func-size-offset: lim. 0 <= 0? OK!
TargetsManager: Loaded targets file OCP_Target.bed
TargetsManager: 2530 target(s) (1544 after merging)
Merged 0 unique comment lines into combined BAM header. Encountered 4 duplicate comments.
SampleManager: Found 1 read group(s) and 1 sample(s).
SampleManager: Primary sample "Sample 1" (set via -g) 1 read group(s)
Found a total of 1 different flow orders of max flow lengths: 500
Recalibration was detected from comment lines in bam file(s):
1 unique blocks of recalibration info detected.
TVC: Parsing Indel Assembly parameters.
                         read-limit =    1000000 (integer, builtin default)
                           kmer-len =         19 (integer, parameters json file)
                      min-var-count =          5 (integer, parameters json file)
                 short-suffix-match =          5 (integer, parameters json file)
                     min-indel-size =          4 (integer, parameters json file)
                      max-hp-length =          8 (integer, parameters json file)
                       min-var-freq =       0.15 (double,  parameters json file)
                      min-var-score =         10 (double,  builtin default)
               relative-strand-bias =        0.8 (double,  parameters json file)
                         output-mnv =          0 (integer, parameters json file)
ERROR: two reads having the same run_id and X/Y: WY9V0:01422:02734 and WY9V0:01422:02734
Maybe multiple runs with the same run id, please fix that
[ Wed 2018-03-21 14:00:13 CST ] ERROR: command failed with status 1
`

Beside,i don't want use GATK Mutect2 or some else tools,i just want to use TS.

**Comment by ipan** [comment]
You can find the demo data here:

http://updates.iontorrent.com/tvc_standalone/tvc-demo.tar.bz2

**Comment by haoziyeung** [comment]
Thanks ,i 'll try right now !
