### ISSUE TITLE
TMAP in singularity

### ISSUE THREAD

**Issue by Tato14** [iontorrent/TS#44]
Hi!
Sorry for the begginer question, I want to use this docker file in my singularity hub but I am not able to run any command from the image (.simg) generated. 

Concretely, I want to use tmap mapper but any try to just see the --help reports that tmap is not a valid command.

Any ideas?
Thanks!

**Comment by uma-ramasubramanian** [comment]
Thank you for your question. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
