### ISSUE TITLE
Problems with TVC

### ISSUE THREAD

**Issue by jmfa** [iontorrent/TS#45]
Dear all, 

I managed to successfully install the standalone version of TVC (v. 5.8-18) using the information provided in the readme. However, every time I try to run TVC i get the following error:
"ERROR: BAM file(s) do not have any read group definitions"

Initially I thought that I had a problem with my dataset, but I get this error regardless of the input files used. For instance, using the demo data available i get the same error. Here's the command used:
python variant_caller_pipeline.py -i ts8466.bam -r ts8466.fasta

Do you have any idea of how I may fix this? perhaps using an older version of TVC?

**Comment by uma-ramasubramanian** [comment]
Thank you for reporting the issue. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
