### ISSUE TITLE
Use of uninitialized value $returnString in concatenation (.) or string at build_genome_index.pl line 141

### ISSUE THREAD

**Issue by Cdk29** [iontorrent/TS#46]
Good evening,

I get the following error when running :

 >perl build_genome_index.pl -f hg38.fa -s human -l H. Sapiens -v hg38 

build_genome_index.pl: problem encountered running command "build_genome_index.pl/validate_reference.pl -f hg38.fa 2>&1"
Failed to execute command: Not a directory

Use of uninitialized value $returnString in concatenation (.) or string at build_genome_index.pl line 141.

build_genome_index.pl: Invalid fasta file supplied, fix and retry.

Died at build_genome_index.pl line 143.

Does someone have a clue about this ? Everything seems to be okay

**Comment by Cdk29** [comment]
Good evening,

I would like to add on my previous post that I have construct the reference genome in the usual way
getting the fasta files from http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/analysisSet/hg38.analysisSet.chroms.tar.gz and using the usual  cat *.fa > hg38.fa to concatenate all chromosomes into one file.

I have also tried today with the fasta file from the human genome from Ensembl but it does not work either.

**Comment by uma-ramasubramanian** [comment]
Thank you for reporting the issue. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
