### ISSUE TITLE
TargetsManager: BED not sorted at position

### ISSUE THREAD

**Issue by rashidma** [iontorrent/TS#47]
I am working with _tvc 5.10-11 (a3f44efe59-4492b243) - Torrent Variant Caller_ to call variants from exome data. The command is as follows-
`tvc --num-threads 10 -r $REF --input-bam $input/SRR5682283_sorted.bam --target-file $input/AmpliseqExome.20141120_effective_regions.nooverlap.bed --output-dir $outdir`

But, i always get the following similar error -

> TargetsManager: BED not sorted at position 0 replaced :6:193238-193809 with :0:68928-69134
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  basic_string::substr

Any help will be highly appreciated. I sorted the BED file with `bedtools sort`. But, no luck.
Thanks

**Comment by uma-ramasubramanian** [comment]
Thank you for reporting the issue. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
