### ISSUE TITLE
liquid biopsy variant calling problems

### ISSUE THREAD

**Issue by lsumoy** [iontorrent/TS#48]
Hi,

I have been trying to call variants on liquid biopsy samples using the variantCaller (TVC) 5.10.0.18 -and then with 5.10.0.20 from within Ion Torrent Suite (ITS) server web interface application and it keeps failing.

We are running samples on 318 chips on a PGM. We had been able to call variants from the ITS  using TVC prior to upgrading the Torrent Suite Software to version 5.10.

Initially we launched the run with a run plan that included the last parameter file used. The error log highlighted:
"ERROR: Fail to process configuration :
ERROR: The plugin does not support the legacy TS-5.2 parameter file that uses "tmol" for tagseq. Please upgrade your run plan and/or parameter file."

I tried out the parameter file found in the web (https://assets.thermofisher.com/TFS-Assets/GC/Reference-Materials/Oncomine_Lung_v1_cfDNA_TVC_parameters.20181220.json)
and keeps giving the same issues.

One surprise is we are no longer able to load the variantCaller plugin (clicking on Data/Plugins/SelectPlugins to run) to perform variant calling analysis after the run or reanalysis has ended. There is the following generic text showing up without the usual  way to enter any parameters or no button allow to start a variant calling plugin analysis execution:

"Torrent Variant Caller 5.10
About Torrent Variant Caller
TVC analyzes mapped reads covering each individual reference base to deduce whether there is sufficient statistical evidence to support calling a SNP or INDEL at a given position. The analysis can be restricted to a subset of the genome by defining targeted regions. If hotspot regions are defined, TVC includes their positions in the report, even if variants have not been specifically identified.
Get more information by visiting Torrent Variant Caller Documentation."

Instead, upon launching a reanalysis from scratch (Data/Report Actions/Reanalyze) it appears that the plugin is available but also with another error popping up when calling the TVC plugin:

"Error: Can not find the uri of the Ampliseq bundle"

Strikingly, the default plans in ITS 5.10 appear to exclude PGM and only mention S550.
We know the analysis can be done through Ion Reporter but is variant calling for oncomine liquid biopsies for the PGM no longer supported using the Torrent Suite variantCaller plugin?

Lauro

**Comment by uma-ramasubramanian** [comment]
Thank you for reporting the issue. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
