### ISSUE TITLE
ubuntu18.04 install TMAP error

### ISSUE THREAD

**Issue by mym88mym** [iontorrent/TS#49]
when I make,the last error information below:
depbase=`echo src/sw/lib/Solution9.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.     -Wall -g -O3 -pthread -msse3 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -MT src/sw/lib/Solution9.o -MD -MP -MF $depbase.Tpo -c -o src/sw/lib/Solution9.o src/sw/lib/Solution9.cpp &&\
mv -f $depbase.Tpo $depbase.Po
src/sw/lib/Solution9.cpp:152:133: error: narrowing conversion of ‘197’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 DShiftedBigData16[16] = {0x68, 0xC5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
                                                                              ^
Makefile:1305: recipe for target 'src/sw/lib/Solution9.o' failed
make[2]: *** [src/sw/lib/Solution9.o] Error 1
make[2]: 离开目录“/home/jy2012/soft/TMAP”
Makefile:1348: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: 离开目录“/home/jy2012/soft/TMAP”
Makefile:632: recipe for target 'all' failed
make: *** [all] Error 2
 
How can I install tmap?

**Comment by mym88mym** [comment]
> when I make,the last error information below:
> depbase=`echo src/sw/lib/Solution9.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;
> g++ -DHAVE_CONFIG_H -I. -Wall -g -O3 -pthread -msse3 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -MT src/sw/lib/Solution9.o -MD -MP -MF $depbase.Tpo -c -o src/sw/lib/Solution9.o src/sw/lib/Solution9.cpp &&
> mv -f $depbase.Tpo $depbase.Po
> src/sw/lib/Solution9.cpp:152:133: error: narrowing conversion of ‘197’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
> DShiftedBigData16[16] = {0x68, 0xC5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
> ^
> Makefile:1305: recipe for target 'src/sw/lib/Solution9.o' failed
> make[2]: *** [src/sw/lib/Solution9.o] Error 1
> make[2]: 离开目录“/home/jy2012/soft/TMAP”
> Makefile:1348: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: 离开目录“/home/jy2012/soft/TMAP”
> Makefile:632: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> How can I install tmap?

**Comment by mym88mym** [comment]
> when I make,the last error information below:
> depbase=`echo src/sw/lib/Solution9.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;
> g++ -DHAVE_CONFIG_H -I. -Wall -g -O3 -pthread -msse3 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -MT src/sw/lib/Solution9.o -MD -MP -MF $depbase.Tpo -c -o src/sw/lib/Solution9.o src/sw/lib/Solution9.cpp &&
> mv -f $depbase.Tpo $depbase.Po
> src/sw/lib/Solution9.cpp:152:133: error: narrowing conversion of ‘197’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
> DShiftedBigData16[16] = {0x68, 0xC5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
> ^
> Makefile:1305: recipe for target 'src/sw/lib/Solution9.o' failed
> make[2]: *** [src/sw/lib/Solution9.o] Error 1
> make[2]: Leaving directory“/home/jy2012/soft/TMAP”
> Makefile:1348: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory“/home/jy2012/soft/TMAP”
> Makefile:632: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> How can I install tmap?

**Comment by lDesiree** [comment]
I m running into the same issue. Did you find a way to solve it? Thanks a lot for your help.
