### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by juefish** [iontorrent/TS#7]
Getting this error when using "git submodule update" command while installing TMAP:

Initialized empty Git repository in /opt/TMAP/src/samtools/.git/
fatal: http://github.com/nh13/samtools.git/info/refs download error - The requested URL returned error: 403
Clone of 'http://github.com/nh13/samtools.git' into submodule path 'src/samtools' failed

Git seems to be there. Any thoughts on what's up?

Thanks,
Nate

**Comment by uma-ramasubramanian** [comment]
Thank you for reporting the issue. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
